# Starship 提示符配置

add_newline = true

[character]
success_symbol = "[❯](bold green)"
error_symbol = "[❯](bold red)"

[directory]
style = "bold blue"
truncation_length = 5

[git_branch]
style = "bold purple"

[git_status]
style = "bold red"

[time]
disabled = false
style = "bold yellow"
format = '[%T]'
